export const headerLength: number = 10;
export const decoder = new TextDecoder('utf-16');
export const englishRegex: RegExp = /^[A-Za-z0-9_]*$/;

export enum Civ {
    Spanish = 1,
    British = 2,
    French = 3,
    Portuguese = 4,
    Dutch = 5,
    Russians = 6,
    Germans = 7,
    Ottoman = 8,
    Haudenosaunee = 9,
    Lakota = 10,
    Aztecs = 11,
    Chinese = 12,
    Japanese = 13,
    Indians = 14,
    Inca = 15,
    Swedes = 16,
    UnitedStates = 17,
    Ethiopians = 18,
    Hausa = 19,
    Mexicans = 20,
    Italians = 21,
    Maltese = 22,
}

export type CivInfo = {
    name: string,
    urlCircle: string,
    urlRectanle: string,
    urlLeft: string,
    idCiv: number,
    homecityJson: string,
}

export const civToInfo = new Map<Civ, CivInfo>([
    [Civ.Spanish, { name: "Spanish", urlCircle: "flag_hc_spanish.png", urlRectanle: "Flag_Spanish.png", urlLeft: "postgame_flag_spanish.png", idCiv: 1, homecityJson: 'homecityspanish' }],
    [Civ.British, { name: "British", urlCircle: "flag_hc_british.png", urlRectanle: "Flag_British.png", urlLeft: "postgame_flag_british.png", idCiv: 2, homecityJson: 'homecitybritish' }],
    [Civ.French, { name: "French", urlCircle: "flag_hc_french.png", urlRectanle: "Flag_French.png", urlLeft: "postgame_flag_french.png", idCiv: 3, homecityJson: 'homecityfrench' }],
    [Civ.Portuguese, { name: "Portuguese", urlCircle: "flag_hc_portuguese.png", urlRectanle: "Flag_Portuguese.png", urlLeft: "postgame_flag_portuguese.png", idCiv: 4, homecityJson: 'homecityportuguese' }],
    [Civ.Dutch, { name: "Dutch", urlCircle: "flag_hc_dutch.png", urlRectanle: "Flag_Dutch.png", urlLeft: "postgame_flag_dutch.png", idCiv: 5, homecityJson: 'homecitydutch' }],
    [Civ.Russians, { name: "Russians", urlCircle: "flag_hc_russian.png", urlRectanle: "Flag_Russian.png", urlLeft: "postgame_flag_russian.png", idCiv: 6, homecityJson: 'homecityrussians' }],
    [Civ.Germans, { name: "Germans", urlCircle: "flag_hc_german.png", urlRectanle: "Flag_German.png", urlLeft: "postgame_flag_german.png", idCiv: 7, homecityJson: 'homecitygerman' }],
    [Civ.Ottoman, { name: "Ottoman", urlCircle: "flag_hc_ottoman.png", urlRectanle: "Flag_Ottoman.png", urlLeft: "postgame_flag_ottoman.png", idCiv: 8, homecityJson: 'homecityottomans' }],
    [Civ.Haudenosaunee, { name: "Haudenosaunee", urlCircle: "flag_hc_iroquois.png", urlRectanle: "Flag_Iroquois.png", urlLeft: "postgame_flag_iroquois.png", idCiv: 9, homecityJson: 'homecityxpiroquois' }],
    [Civ.Lakota, { name: "Lakota", urlCircle: "flag_hc_sioux.png", urlRectanle: "Flag_Sioux.png", urlLeft: "postgame_flag_sioux.png", idCiv: 10, homecityJson: 'homecityxpsioux' }],
    [Civ.Aztecs, { name: "Aztecs", urlCircle: "flag_hc_aztec.png", urlRectanle: "Flag_Aztec.png", urlLeft: "postgame_flag_aztec.png", idCiv: 11, homecityJson: 'homecityxpaztec' }],
    [Civ.Chinese, { name: "Chinese", urlCircle: "flag_hc_chinese.png", urlRectanle: "Flag_Chinese.png", urlLeft: "postgame_flag_chinese.png", idCiv: 12, homecityJson: 'homecitychinese' }],
    [Civ.Japanese, { name: "Japanese", urlCircle: "flag_hc_japanese.png", urlRectanle: "Flag_Japanese.png", urlLeft: "postgame_flag_japanese.png", idCiv: 13, homecityJson: 'homecityjapanese' }],
    [Civ.Indians, { name: "Indians", urlCircle: "flag_hc_indian.png", urlRectanle: "Flag_Indian.png", urlLeft: "postgame_flag_indian.png", idCiv: 14, homecityJson: 'homecityindians' }],
    [Civ.Inca, { name: "Inca", urlCircle: "flag_hc_inca.png", urlRectanle: "Flag_Incan.png", urlLeft: "postgame_flag_inca.png", idCiv: 15, homecityJson: 'homecitydeinca' }],
    [Civ.Swedes, { name: "Swedes", urlCircle: "flag_hc_swedish.png", urlRectanle: "Flag_Swedish.png", urlLeft: "postgame_flag_swedish.png", idCiv: 16, homecityJson: 'homecityswedish' }],
    [Civ.UnitedStates, { name: "United States", urlCircle: "flag_hc_american.png", urlRectanle: "Flag_American.png", urlLeft: "postgame_flag_american.png", idCiv: 17, homecityJson: 'homecityamericans' }],
    [Civ.Ethiopians, { name: "Ethiopians", urlCircle: "flag_hc_ethiopian.png", urlRectanle: "Flag_Ethiopian.png", urlLeft: "postgame_flag_ethiopian.png", idCiv: 18, homecityJson: 'homecityethiopians' }],
    [Civ.Hausa, { name: "Hausa", urlCircle: "flag_hc_hausa.png", urlRectanle: "Flag_Hausa.png", urlLeft: "postgame_flag_hausa.png", idCiv: 19, homecityJson: 'homecityhausa' }],
    [Civ.Mexicans, { name: "Mexicans", urlCircle: "flag_hc_mexican.png", urlRectanle: "Flag_Mexican.png", urlLeft: "postgame_flag_mexican.png", idCiv: 20, homecityJson: 'homecitymexicans' }],
    [Civ.Italians, { name: "Italians", urlCircle: "flag_hc_italian.png", urlRectanle: "Flag_Italian.png", urlLeft: "postgame_flag_italian.png", idCiv: 21, homecityJson: 'homecityitalians' }],
    [Civ.Maltese, { name: "Maltese", urlCircle: "flag_hc_maltese.png", urlRectanle: "Flag_Maltese.png", urlLeft: "postgame_flag_maltese.png", idCiv: 22, homecityJson: 'homecitymaltese' }],
]);

export let civMap = new Map([
    [1, Civ.Spanish],
    [2, Civ.British],
    [3, Civ.French],
    [4, Civ.Portuguese],
    [5, Civ.Dutch],
    [6, Civ.Russians],
    [7, Civ.Germans],
    [8, Civ.Ottoman],
    [15, Civ.Haudenosaunee],
    [16, Civ.Lakota],
    [17, Civ.Aztecs],
    [19, Civ.Japanese],
    [20, Civ.Chinese],
    [21, Civ.Indians],
    [27, Civ.Inca],
    [28, Civ.Swedes],
    [38, Civ.UnitedStates],
    [39, Civ.Ethiopians],
    [40, Civ.Hausa],
    [42, Civ.Mexicans],
    [44, Civ.Italians],
    [45, Civ.Maltese],
]);